
import java.sql.ResultSetMetaData;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
//-----------------------------------------------------------------------------------------------------------------------------------------------------
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


//-----------------------------------------------------------------------------------------------------------------------------------------------------
public class Customer extends javax.swing.JFrame {

    public Customer() {
        initComponents(); //
        Connect(); //sql connection
        autoId();  //increment reserve , roomno
        show_CustomerTble(); //displaying out input data on table
        
     
    }
    Connection con = null;
    PreparedStatement pst = null;
    DefaultTableModel d;
//    ResultSet rs = null;
//-----------------------------------------------------------------------------------------------------------------------------------------------------
  
    
    
 
     
 //----------------------------------------------------------------------------------------------------------------------------------------------------- 
    public void Connect() //Calling Connect Method, this is our database connection when the form is loaded
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");                      
                //obj con, database is reside in our local host and inside localhost whats database name whic is luxuryhotel  user=root password=blank
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/luxuryhotel","root","");
            
                         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
//-----------------------------------------------------------------------------------------------------------------------------------------------------
 
    
    
 
    
 //-----------------------------------------------------------------------------------------------------------------------------------------------------
    
    public void autoId()
    {
        try {
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("select MAX(Cr) from customerTble");
            rs.next();
            rs.getString("MAX(Cr)");
            if(rs.getString("MAX(Cr)") ==  null)
            {
                Cr.setText("M0001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("MAX(Cr)").substring(1, rs.getString("MAX(Cr)").length()));
                id++;
                Cr.setText("M0" + String.format("%03d", id)); // add "%03d" to add 3 leading zeros in an Integer.
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
//-----------------------------------------------------------------------------------------------------------------------------------------------------
    
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
  //-----------------------------------------------------------------------------------------------------------------------------------------------------
        //displaying output in our table 
    public void show_CustomerTble()                                    
        {
        try {
            pst = con.prepareStatement("select * from CustomerTble");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int c = rsmd.getColumnCount();    
            d = (DefaultTableModel)CustomerTble.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for (int i=1; i<=c; i++)
                {
                    v2.add(rs.getString("Cr"));
                    v2.add(rs.getString("Cfname"));
                    v2.add(rs.getString("Cgen"));
                    v2.add(rs.getString("Ccont"));
                    v2.add(rs.getString("Caddress"));
                    v2.add(rs.getString("Ccity"));
                    v2.add(rs.getString("Ccnic"));
                   
                }                    
                    d.addRow(v2);                
            }           
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        }     
//-----------------------------------------------------------------------------------------------------------------------------------------------------
  
   
    
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTble = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Caddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Ccity = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Cfname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Cr = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Cgen = new javax.swing.JComboBox<>();
        EditBtn = new javax.swing.JButton();
        Ccont = new javax.swing.JTextField();
        Ccnic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CustomerTble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reserve ID ", "Full Name", "Gender", "Contact No.", "Address", "City", "CNIC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CustomerTble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTble);
        if (CustomerTble.getColumnModel().getColumnCount() > 0) {
            CustomerTble.getColumnModel().getColumn(0).setMinWidth(15);
            CustomerTble.getColumnModel().getColumn(0).setMaxWidth(65);
            CustomerTble.getColumnModel().getColumn(1).setMinWidth(70);
            CustomerTble.getColumnModel().getColumn(1).setMaxWidth(90);
            CustomerTble.getColumnModel().getColumn(2).setMinWidth(5);
            CustomerTble.getColumnModel().getColumn(2).setMaxWidth(60);
            CustomerTble.getColumnModel().getColumn(3).setMinWidth(90);
            CustomerTble.getColumnModel().getColumn(3).setMaxWidth(120);
            CustomerTble.getColumnModel().getColumn(4).setMinWidth(90);
            CustomerTble.getColumnModel().getColumn(4).setMaxWidth(120);
            CustomerTble.getColumnModel().getColumn(5).setMinWidth(40);
            CustomerTble.getColumnModel().getColumn(5).setMaxWidth(80);
            CustomerTble.getColumnModel().getColumn(6).setMinWidth(90);
            CustomerTble.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 660, 370));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("ZARH LUXURY HOTEL MANAGEMENT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 47, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Current Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 130, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Gender:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 80, 40));

        Caddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaddressActionPerformed(evt);
            }
        });
        getContentPane().add(Caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 120, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Contact No:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 100, 30));

        Ccity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcityActionPerformed(evt);
            }
        });
        getContentPane().add(Ccity, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 120, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("City:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 60, 30));

        Cfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CfnameActionPerformed(evt);
            }
        });
        getContentPane().add(Cfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 120, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Cnic:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 80, 30));

        add1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add1.setText("ADD");
        add1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 80, 30));

        deletebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 660, 80, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 660, 80, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Customer Information");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 390, 50));

        Cr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cr.setForeground(new java.awt.Color(204, 255, 255));
        Cr.setText("Cr");
        getContentPane().add(Cr, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 90, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Full Name:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 100, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Reserve ID");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuxuryImages/next.PNG"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuxuryImages/back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        Cgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", "Other" }));
        Cgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CgenActionPerformed(evt);
            }
        });
        getContentPane().add(Cgen, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 120, 30));

        EditBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditBtn.setText("EDIT");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 660, 80, 30));
        getContentPane().add(Ccont, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 120, 30));
        getContentPane().add(Ccnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 572, 120, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuxuryImages/blueBackground.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 1230, 510));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuxuryImages/background3.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1330, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CfnameActionPerformed

    private void CustomerTbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTbleMouseClicked
        // TODO add your handling code here:
         d = (DefaultTableModel)CustomerTble.getModel();
        int selectIndex = CustomerTble.getSelectedRow();
        
        Cr.setText(d.getValueAt(selectIndex, 0).toString());
        Cfname.setText(d.getValueAt(selectIndex, 1).toString());
        Cgen.setSelectedItem(d.getValueAt(selectIndex, 2).toString());
        Ccont.setText(d.getValueAt(selectIndex, 3).toString());
        Caddress.setText(d.getValueAt(selectIndex, 4).toString());
        Ccity.setText(d.getValueAt(selectIndex, 5).toString());
        Ccnic.setText(d.getValueAt(selectIndex, 6).toString());
        add1.setEnabled(false);

    }//GEN-LAST:event_CustomerTbleMouseClicked

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        
        String reserveNo = Cr.getText();
        String fulln = Cfname.getText();
        String gender = Cgen.getSelectedItem().toString();
        String contact = Ccont.getText();
        String address = Caddress.getText();
        String city = Ccity.getText();
        String cnic = Ccnic.getText();
             
        
//if(Cfname.getText().isEmpty() || Cgen.getSelectedIndex() == -1 || Ccont.getText().isEmpty() || Caddress.getText().isEmpty() || 
//    Ccity.getText().isEmpty() || Ccnic.getText().isEmpty() || Ccat.getSelectedIndex() == -1 || Croom.getSelectedIndex() == -1 || Cprice.getText().isEmpty())  
//        {
//            JOptionPane.showMessageDialog(this, "Missing Data!!!");            
//        }
//
//else{
        try {
            pst = con.prepareStatement("insert into customerTble(Cr, Cfname, Cgen, Ccont, Caddress, Ccity, Ccnic) values(?,?,?,?,?,?,?)");
            //prepared statement all of the strings by setString method..
           
            pst.setString(1, reserveNo);
            pst.setString(2, fulln);
            pst.setString(3, gender);
            pst.setString(4, contact);
            pst.setString(5, address);
            pst.setString(6, city);
            pst.setString(7, cnic);
      
            pst.executeUpdate(); //here our pst statement will execute.
            //displaying message of Room is Added Successfully..
            JOptionPane.showMessageDialog(this, "Customer Information Added !!");
            
            //here we are clearing all the input data from our roomTble which will set to blank
            Cfname.setText("");
            Caddress.setText("");
            Ccont.setText(""); 
            Ccity.setText("");
            Ccnic.setText("");   
            Cgen.setSelectedIndex(-1);
            autoId();
            show_CustomerTble();            
           
            
           
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }       
        //Add button Functionality is here..
   
       
    }//GEN-LAST:event_add1ActionPerformed
//-----------------------------------------------------------------------------------------------------------------------------------------------------    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         //here we are clearing all the input data from our roomTble which will set to blank
            Cfname.setText("");
            Caddress.setText("");
            Ccont.setText("");
            Ccity.setText("");
            Ccnic.setText("");         
            Cgen.setSelectedIndex(-1); 
            autoId();
            show_CustomerTble();
            add1.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //edit
               //        if(Rcat.getSelectedIndex() == -1 || Rroom.getSelectedIndex() == -1 || Rstat.getSelectedIndex() == -1 || Rdur.getSelectedIndex() == -1 ||
            //            Rbdate.getText().isEmpty() || Rprice.getText().isEmpty())
        //        {
            //            JOptionPane.showMessageDialog(this, "Missing Edit Data!!!");
            //        }
        //        else
        //        {
    
    
    
    
    
    
    
    
    
   
    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
         
          String reserveID = Cr.getText();
        try {
            pst = con.prepareStatement("delete from customerTble where Cr = ?");
            
            pst.setString(1, reserveID);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Customer Information Deleted !!"); 
            
            Cfname.setText("");
            Caddress.setText("");
            Ccont.setText("");
            Ccity.setText("");
            Ccnic.setText("");        
            Cgen.setSelectedIndex(-1);
            autoId();
             show_CustomerTble();
             add1.setEnabled(true);
             
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_deletebtnActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new InfoUnchangable().setVisible(true);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new AdminPanel().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void CaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaddressActionPerformed

    private void CcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CcityActionPerformed

    private void CgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CgenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CgenActionPerformed

    
    
    
    
    
    
    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        //calling variable with their method and storing them into new variable..    
        String reserveNo = Cr.getText();
        String fulln = Cfname.getText();
        String genderr = Cgen.getSelectedItem().toString();
        String contact = Ccont.getText();
        String address = Caddress.getText();
        String city = Ccity.getText();
        String cnic = Ccnic.getText();

            try {
                pst = con.prepareStatement("update customerTble set Cfname = ?, Cgen = ?, Ccont = ?, Caddress = ?, Ccity = ?, Ccnic = ? where Cr = ?");
                //prepared statement all of the strings by setString method..
              
                pst.setString(1, fulln);
                pst.setString(2, genderr);
                pst.setString(3, contact);
                pst.setString(4, address);
                pst.setString(5, city);
                pst.setString(6, cnic);   
                pst.setString(7, reserveNo);
                pst.executeUpdate(); //here our pst statement will execute.
                //displaying message of Room is Added Successfully..
                JOptionPane.showMessageDialog(this, "Customer Information Edited !!");

                //here we are clearing all the input data from our roomTble which will set to blank
                Cfname.setText("");
                Cgen.setSelectedIndex(-1);
                Ccont.setText("");
                Caddress.setText("");              
                Ccity.setText("");
                Ccnic.setText("");                         
                autoId();
                show_CustomerTble();
//                add1.setEnabled(false);

            } catch (SQLException ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
 
      
    }//GEN-LAST:event_EditBtnActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Caddress;
    private javax.swing.JTextField Ccity;
    private javax.swing.JTextField Ccnic;
    private javax.swing.JTextField Ccont;
    private javax.swing.JTextField Cfname;
    private javax.swing.JComboBox<String> Cgen;
    private javax.swing.JLabel Cr;
    private javax.swing.JTable CustomerTble;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton add1;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
