
import java.sql.ResultSetMetaData;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class InfoUnchangable extends javax.swing.JFrame {

    /**
     * Creates new form InfoUnchangable
     */
    public InfoUnchangable() {
        initComponents();
        Connect();
        show_CustomerTble1(); 
        roomCategory();  //getting data from room tab      
        RoomNo();       //getting data from room tab 
        Amount();
    }
    Connection con = null;
    PreparedStatement pst = null;
    DefaultTableModel d;
//-----------------------------------------------------------------------------------------------------------------------------------------------------
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //----------------------------------------------------------------------------------------------------------------------------------------------------- 
    public void Connect() //Calling Connect Method, this is our database connection when the form is loaded
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");                      
                //obj con, database is reside in our local host and inside localhost whats database name whic is luxuryhotel  user=root password=blank
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/luxuryhotel","root","");
            
                         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }
//-----------------------------------------------------------------------------------------------------------------------------------------------------
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ccheckin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ccheckout = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        Ccat = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        Croom = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        Cprice = new javax.swing.JComboBox<>();
        add1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTble1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Ccheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 140, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Check out");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 110, -1));
        getContentPane().add(Ccheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 140, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Category");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, 40));

        Ccat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ccat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CcatActionPerformed(evt);
            }
        });
        getContentPane().add(Ccat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 140, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Room No");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        Croom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CroomActionPerformed(evt);
            }
        });
        getContentPane().add(Croom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 140, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Amount:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 70, 30));

        getContentPane().add(Cprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 140, 30));

        add1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add1.setText("ADD");
        add1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        getContentPane().add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 80, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 80, 30));

        CustomerTble1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Check In", "Check Out", "Category", "Room No", "Amount"
            }
        ));
        jScrollPane1.setViewportView(CustomerTble1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 580, 310));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuxuryImages/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Customer Room Information(Unchangeable)");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 770, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LuxuryImages/blueBackground.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 990, 490));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("ZARH LUXURY HOTEL MANAGEMENT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background3.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -1, 1330, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     //-----------------------------------------------------------------------------------------------------------------------------------------------------
        //displaying output in our table 
    public void show_CustomerTble1()                                    
        {
        try {
            pst = con.prepareStatement("select * from CustomerTble1");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int c = rsmd.getColumnCount();    
            d = (DefaultTableModel)CustomerTble1.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for (int i=1; i<=c; i++)
                {                   
                    v2.add(rs.getString("Ccheckin"));
                    v2.add(rs.getString("Ccheckout"));
                    v2.add(rs.getString("Ccat"));
                    v2.add(rs.getString("Croom"));
                    v2.add(rs.getString("Cprice"));
                }                    
                    d.addRow(v2);                
            }           
        } catch (SQLException ex) {
            Logger.getLogger(InfoUnchangable.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        }     
//-----------------------------------------------------------------------------------------------------------------------------------------------------
    
    
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    public void roomCategory() 
     {

        try {      
                pst = con.prepareStatement("select Distinct Rcat from roomTble"); 
                ResultSet rs = pst.executeQuery();
                Ccat.removeAllItems();
                while(rs.next())
                {
                    Ccat.addItem(rs.getString("Rcat"));
                }
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }      
    }        
    
    
     public void RoomNo() {
         try {      
                pst = con.prepareStatement("select Distinct Rb from roomTble");
                ResultSet rs = pst.executeQuery();
                
                while(rs.next())
                {
                    Croom.addItem(rs.getString("Rb"));
                }
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
     }
     
     
      public void Amount() {
         try {      
                pst = con.prepareStatement("select Distinct Rprice from roomTble");
                ResultSet rs = pst.executeQuery();
                
                while(rs.next())
                {
                    Cprice.addItem(rs.getString("Rprice"));
                }
           
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
     }
      
      
      
    private void CcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CcatActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CcatActionPerformed

    private void CroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CroomActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CroomActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
       
        SimpleDateFormat dfi = new SimpleDateFormat("yyyy-MM-dd");
        String checkin = dfi.format(Ccheckin.getDate());       
        SimpleDateFormat dfo = new SimpleDateFormat("yyyy-MM-dd");
        String checkout = dfo.format(Ccheckout.getDate());
        String category = Ccat.getSelectedItem().toString();
        String roomno = Croom.getSelectedItem().toString();
        String amount = Cprice.getSelectedItem().toString();  
        
        //if(Cfname.getText().isEmpty() || Cgen.getSelectedIndex() == -1 || Ccont.getText().isEmpty() || Caddress.getText().isEmpty() || 
//    Ccity.getText().isEmpty() || Ccnic.getText().isEmpty() || Ccat.getSelectedIndex() == -1 || Croom.getSelectedIndex() == -1 || Cprice.getText().isEmpty())  
//        {
//            JOptionPane.showMessageDialog(this, "Missing Data!!!");            
//        }
//
//else{
    
              try {
            pst = con.prepareStatement("insert into customerTble1(Ccheckin, Ccheckout, Ccat, Croom, Cprice) values(?,?,?,?,?)");
            //prepared statement all of the strings by setString method..
           
            pst.setString(1, checkin);
            pst.setString(2, checkout);
            pst.setString(3, category);
            pst.setString(4, roomno);
            pst.setString(5, amount);
      
            pst.executeUpdate(); //here our pst statement will execute.
            //displaying message of Room is Added Successfully..
            JOptionPane.showMessageDialog(this, "Customer Room Information Added !!");
            
            //here we are clearing all the input data from our roomTble which will set to blank      
            Cprice.setSelectedIndex(-1);             
            Ccat.setSelectedIndex(-1);           
            Croom.setSelectedIndex(-1);            
            show_CustomerTble1();
           
        } catch (SQLException ex) {
            Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
        }       
        //Add button Functionality is here..
    
    
//-----------------------------------------------------------------------------------------------------------------------------------------------------

     
    }//GEN-LAST:event_add1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //here we are clearing all the input data from our roomTble which will set to blank      
        Cprice.setSelectedIndex(-1);
        Ccat.setSelectedIndex(-1);
        Croom.setSelectedIndex(-1);
        show_CustomerTble1();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new Customer().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoUnchangable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoUnchangable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoUnchangable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoUnchangable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoUnchangable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ccat;
    private com.toedter.calendar.JDateChooser Ccheckin;
    private com.toedter.calendar.JDateChooser Ccheckout;
    private javax.swing.JComboBox<String> Cprice;
    private javax.swing.JComboBox<String> Croom;
    private javax.swing.JTable CustomerTble1;
    private javax.swing.JButton add1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
